[package]
name = "shelf-web"
version = "0.1.0"
authors = ["David Li <li.davidm96@gmail.com>"]
edition = "2018"

[dependencies]
app_dirs = "1.2"
clap = "2.33"
tera = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
warp = "0.1.19"

[dependencies.shelf]
path = "../shelf"
