name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Git
      run: git config --global user.name "David Li"
    - name: Set Up Git
      run: git config --global user.email "li.davidm96@gmail.com"
    - name: Build
      run: cargo build
      working-directory: shelf
    - name: Run tests
      run: cargo test
      working-directory: shelf
    - name: Clippy
      run: cargo clippy
      working-directory: shelf
